### ISSUE TITLE
Right clicked on the "Spotify Connected" text

### ISSUE THREAD

**Issue by angiioh** [studiowebux/obsidian-spotify-link#12]
Hi! Been enjoying your plugin, but I wanted to report an issue. 

I'm relatively new to Obsidian, so I was right clicking on the Spotify Connected text on the status bar at the bottom of Obsidian to see if there was an option to hide that text. Instead, it suddenly rapidly opened tab after tab of my spotify page in my browser. Closing Obsidian didn't stop it and closing my browser didn't either-- I ended up restarting my computer! It was overwhelming and hilarious. 

Once my computer booted again, going back into Obsidian didn't trigger it again and I was able to close the 80+ tabs. Let me know if I can get you any more information for troubleshooting. Thanks!

**Comment by studiowebux** [comment]
Hello ! 

Thanks for reporting this issue, 
I simply removed that "feature" it was only for testing purposes when I was building the core of the plugin

So I pushed the version 1.4.1 for that

**Comment by angiioh** [comment]
Thank you! Appreciate your time.
