### ISSUE TITLE
Feature Request: select file as template and create new note

### ISSUE THREAD

**Issue by starfetch** [studiowebux/obsidian-spotify-link#14]
Hi, thanks for creating this plugin, it's working great.
I'm trying to use it as a way to get metadata about songs I like into Obsidian (like I do with books, films, etc), and it would be great if there was an option to select a template file instead of having to copy the entire template into the tiny textbox.
Additionally, a way to create a new note directly from this template would be very handy as well (right now I append to a new note, but some templater commands do not trigger properly this way).

Thanks in advance and keep up the great work.

**Comment by studiowebux** [comment]
Hello, 
Thanks for your Feature request !

I will take a look this week and update this ticket.

---

**The first feature** I will have to take a look if I can add the feature without breaking the existing one (i think I did it to support that approach), what I have in mind is to allow to read files with a special name for example, `option_name.template.md`, these files will have to be store either in the vault or in the plugin directory, which one do you prefer ?

**The second feature**, should be easy as I did it with my other plugin.

**Comment by starfetch** [comment]
> **The first feature** I will have to take a look if I can add the feature without breaking the existing one (i think I did it to support that approach), what I have in mind is to allow to read files with a special name for example, `option_name.template.md`, these files will have to be store either in the vault or in the plugin directory, which one do you prefer ?

My preference would be in the vault, since that's easier to edit (and I have a `Templates` folder already). Do you think it's possible to choose an arbitrary file as a template, as for example done by the [`Book Search` plugin ](https://github.com/anpigon/obsidian-book-search-plugin) or the MediaDB plugin?

> **The second feature**, should be easy as I did it with my other plugin.

Great to hear!

Thanks for taking the time to look into this.

**Comment by studiowebux** [comment]
hello again 👋 

So i had free time tonight, 

I created this PR : https://github.com/studiowebux/obsidian-spotify-link/pull/15#issue-2587323709
(I dont expect a code review or anything, just validate the description I wrote if it is ok for you) 

if so, I will prepare a release to let you test 

Thanks !

**Comment by starfetch** [comment]
I had a look, and only the first two paragraphs about the menu are not entirely clear to me: Does it mean that new commands are added to the command palette or not?

The rest looks good, thanks for your time!

**Comment by studiowebux** [comment]
@starfetch 

For the menu:
- I added this : 
![image](https://github.com/user-attachments/assets/42f6abd3-2d9d-4693-a266-82993b396c04)

TODOs:
- I will add the 4 items in the **command palette** as well (_i forgot that one_), (the CMD+P panel)

Clarification: The menu items can be enabled/disabled in case its clutter the right click menu (the screenshot).

**Comment by studiowebux** [comment]
Hello !

I released v1.5.1 (you can update directly in obsidian), 

let me know if it has everything and if it works as you expected.

Thanks

**Comment by starfetch** [comment]
Hi, creating a new note with these commands works great, thanks a ton! This will make taking note of songs so much easier.
[Now it would be perfect if there was a toggle to open the new note directly after creation (sorry, feature creep, only if it's a simple addition).]

Using a template file took me a few minutes to figure out (first I didn't see the new description above the textbox), but that also works a treat. 
A few things that should be documented which were not immediately obvious to me:
- path to file needs to include the filename extension (.md), otherwise it just prints that as text
- if a folder is chosen to save new files in, that folder has to exist already
- the command fails silently if the folder doesn't exist

Thank you so much for implementing this so quickly and nicely, your work is greatly appreciated.

**Comment by studiowebux** [comment]
TODOS:

- [ ]  Add toggle to open new note upon creation
- [ ] auto append .md when not provided to improve UX
- [ ] create the folder if not exists
- [ ] try..catch error correctly and print a notice
- [ ] Add instructions for path vs inline template in the template documentation
- [ ] Update the official documentation with examples and new features

For this one: 
> Using a template file took me a few minutes to figure out (first I didn't see the new description above the textbox), but that also works a treat.

Hum I added it on both field description. I can add details about it in the section above (with template options)

I didnt update the "official" documentation yet (the dedicated website)

Will try to tackle all todos this week (maybe over the weekend as well)

**Comment by studiowebux** [comment]
Finally that was simple.

released 1.5.2 (still have to update the official doc, will do after everything is good)

Will wait your feedback
Thanks again !

**Comment by elvarb** [comment]
> Additionally, a way to create a new note directly from this template would be very handy as well (right now I append to a new note, but some templater commands do not trigger properly this way).

Just something to explore, you can use the Quick Add plugin to create a new note from a templater file and then add a link to it to the currently open file.

**Comment by starfetch** [comment]
@studiowebux Sorry it took me so long to answer, your additions are working great!
Thank you so much for implementing these features, they have greatly improved my workflow, and thanks for the great communication.
Keep up the good work!
