### ISSUE TITLE
Custom {{timestamp}} formatting, or change default to ISO8601

### ISSUE THREAD

**Issue by elvarb** [studiowebux/obsidian-spotify-link#16]
Current use of {{timestamp}} will provide a timestamp as: Sat Oct 26 2024 - 13:02:33

Would be preferable to have this as standard ISO8601 by default: 2024-10-26T13:02:33Z

Best would be to allow for customization, for example in a daily note you want perhaps to have the time only as the date would be redundant. Example could be {{timestamp(HH:mm)}}

**Comment by studiowebux** [comment]
Hello @elvarb !

Thanks for opening this feature request

To avoid rewritting everything and make regexes for the dates and time, I simply did the following:

**Template:**
```md
**Timestamp tests:**

timestamp: {{ timestamp }}
timestampz: {{ timestampz }}
timestamp(HH:mm): {{ timestamp(HH:mm) }}
timestampz(HH:mm): {{ timestampz(HH:mm) }}
```

**Output:** 
```md
**Timestamp tests:**

timestamp: Tue Oct 29 2024 - 7:23:11 PM
timestampz: 2024-10-29T23:23:11.746Z
timestamp(HH:mm): 19:23
timestampz(HH:mm): 23:23
```

I implemented it for tracks and podcasts

Does it work for you ?

**Comment by elvarb** [comment]
If you added one version of the timestamp that would only include the current day in YYYY-MM-DD format then users can combine that with the HH:mm timestamp to fit all their needs.

**Comment by studiowebux** [comment]
So I redid the approach this way (i think it covers everything, including what I had before)

**Input**

```md
timestamp : {{ timestamp }}
timestamp(YYYY-MM-DD) : {{ timestamp(YYYY-MM-DD) }}
timestamp(YYYY-MM-DD HH:mm) : {{ timestamp(YYYY-MM-DD HH:mm) }}
timestamp(HH:mm) : {{ timestamp(HH:mm) }}

timestampz : {{ timestampz }}
timestampz(YYYY-MM-DD) : {{ timestampz(YYYY-MM-DD) }}
timestampz(YYYY-MM-DD HH:mm) : {{ timestampz(YYYY-MM-DD HH:mm) }}
timestampz(HH:mm) : {{ timestampz(HH:mm) }}
```

**Output**

```md
timestamp : Wed Oct 30 2024 - 8:35:15 PM
timestamp(YYYY-MM-DD) : 2024-10-30
timestamp(YYYY-MM-DD HH:mm) : 2024-10-30 20:35
timestamp(HH:mm) : 20:35

timestampz : 2024-10-31T00:35:15.124Z
timestampz(YYYY-MM-DD) : 2024-10-31
timestampz(YYYY-MM-DD HH:mm) : 2024-10-31 00:35
timestampz(HH:mm) : 00:35
```

I used only one regex and handling all the cases.

Does it wprk better for you ?
