### ISSUE TITLE
Spotify specs

### ISSUE THREAD

**Issue by kmaustral** [studiowebux/obsidian-spotify-link#2]
What Redirect URI should we include?
![image](https://github.com/studiowebux/obsidian-spotify-link/assets/73867063/d063aef0-6222-4586-bc56-6ae569a3689c)

**Comment by studiowebux** [comment]
Hello

Sorry about that, i will update the documentation tomorrow

The redirect uri is : obsidian://spotify-auth/

**Comment by studiowebux** [comment]
Updated the documentation at : 
https://studiowebux.github.io/obsidian-plugins-docs/docs/spotify-link/configuration/

Thanks for reporting this !

**Comment by kmaustral** [comment]
Thanks. It's still not connecting. Should tick a particular API in the second part of the screen?

**Comment by studiowebux** [comment]
Yes it should open your browser to authorize the application.

After copying the _client id_ and _secret id_ in the obsidian plugin settings, 
you can click the Spotify logo (left bar in obsidian)
then it will open the browser (I tested only on Iphone and MacOS, so in my case it is Safari)
Then you need to authorize the app and after that it will go back automatically to obsidian (using the redirect URI) to setup the login. and you should see a popup saying successfully connected (same as in the footer in obsidian, only on desktop app)

Extra details: 
Optionally you can change the  _state_
You should not have to change the _Scopes_

Let me know if you have issues following these steps
thanks!

**Comment by kmaustral** [comment]
Thanks. It was clicking on the Spotify logo which was the missing step. You
might like to highlight that.

It would be great to be able to customise the information from Spotify to
be able to include details like album name, but not track progress.

I look forward to seeing how you develop this useful plugin.

Kevin

**Comment by studiowebux** [comment]
I've updated the documentation with screenshots: https://studiowebux.github.io/obsidian-plugins-docs/docs/spotify-link/steps

 and improved the "first time setup" page : https://studiowebux.github.io/obsidian-plugins-docs/docs/spotify-link/spotify
