### ISSUE TITLE
Feature Request: Multiple artists in one song that can be backlinked 

### ISSUE THREAD

**Issue by funkenhausen** [studiowebux/obsidian-spotify-link#22]
Been enjoying this plugin for my own wiki of songs and albums. I would like to request for a feature though. 

When I do this

```
artists:
  - "[[{{ artists }}]]" 
```

and the song has multiple artists, the filename has all of the artists instead of having artists with their separate file. 

What the plugin does right now is: 
```
artists:
  - "[[Artist1, Artist2]]" 
```

I want somehow have an option to be instead be this: 
```
artists:
  - "[[Artist1]]"
  - "[[Artist2]]"
  ```
  
Thanks for making this plugin btw

**Comment by studiowebux** [comment]
Hello !

Thanks for this feature request.

I did a first pass, will do more tests before releasing.

Defining your template:

**templates/Track.md**
```md
Artists:
{{ artists_formatted:  - [[:]] }}
```

**Prefix** is `:  - [[`
**Suffix** is`:]]`

**Output:**

```md
Artists: 
  - [[Artist]]
  - [[Artist]]
```

The format is as follow: `{{ artists_formatted:PREFIX:SUFFIX }}`

The `:` symbol might behave weirdly if you need it as a prefix/suffix. Otherwise it should work and create the link automatically.

Will update this ticket when I release it, will try later today.

**Comment by studiowebux** [comment]
Release 1.9.0 🎉
 https://github.com/studiowebux/obsidian-spotify-link/releases/tag/1.9.0

**The template exmaple if needed** : https://github.com/studiowebux/obsidian-spotify-link/blob/8881e2fba0d7b45df2f1a63fd41d2d85f70ab804/examples/template_track.md?plain=1#L37

@funkenhausen

**Comment by funkenhausen** [comment]
Thanks for the fast reply! Is there any way to make this work for frontmatter / properties of the note? Right now when i have it like this (i can't remove the ' symbol because of frontmatter): 
```
artists: '{{ artists_formatted:  - "[[:]]" }}'
```
it outputs this: 
```
artists: '  - "[[Artist1]]"
  - "[[Artist2]]"'
```
it has that one quote symbol before and after it. and also, it's not formatted for properties because of the weird spacing that it outputs. so it outputs this:
```
artists: '  - "[[Artist1]]"
  - "[[Artist2]]"'
```
when it should be outputting this: 
```
artists: 
- "[[Artist1]]"
- "[[Artist2]]"
```

Is there any way to format it like that? Thanks for the efforts once again

**Comment by studiowebux** [comment]
Hello !

The first thing I see is for the first item I do not do add an enter (\n), this is why the output looks like this: `artists: '  - "[[Artist1]]"`
I was doing something like this when testing:

```md
artists: 
'{{ artists_formatted:  - "[[:]]" }}'
```

For the second thing, I am not familiar with frontmatter / properties.
Can you share your template or parts of it so I can try to adapt the plugin to work with it, if it is possible ?

This plugin searches for a pattern and replaces for the spotify content, it does not do anything special for the added single quotes. Probably why they are left in the output 🤔 

Will wait for your input.

**Comment by funkenhausen** [comment]
[{{ song_name }}.md](https://github.com/user-attachments/files/17972902/song_name.md)

Sure! This is the properties of my template for adding songs. In the properties of the note which is:
```
---
artists: '{{ artists_formatted:  - "[[:]]" }}'
album: "[[{{ album }}]]"
url: "{{ song_link }}"
cover: "{{ album_cover_link_large }}"
tags:
  - songs
---
```
the artists are listed there. If for example, I would add a song using this template, it would output: 
```
---
artists: '  - "[[Kendrick Lamar]]"
  - "[[Baby Keem]]"
  - "[[Sam Dew]]"'
album: "[[Mr. Morale & The Big Steppers]]"
url: "[Savior - Kendrick Lamar, Baby Keem, Sam Dew](https://open.spotify.com/track/3drdWsJKiVCSQ2gKhd9BDT)"
cover: "[Cover - Mr. Morale & The Big Steppers](https://i.scdn.co/image/ab67616d0000b2732e02117d76426a08ac7c174f)"
tags:
  - songs
---
![Mr. Morale & The Big Steppers](https://i.scdn.co/image/ab67616d0000b2732e02117d76426a08ac7c174f))
```
which visually it translates to:
![image](https://github.com/user-attachments/assets/dbb801b0-9e16-4ccb-992e-04ce62f86e9e)
when it should be:
```
---
artists: 
- "[[Kendrick Lamar]]"
- "[[Baby Keem]]"
- "[[Sam Dew]]"
album: "[[Mr. Morale & The Big Steppers]]"
url: "[Savior - Kendrick Lamar, Baby Keem, Sam Dew](https://open.spotify.com/track/3drdWsJKiVCSQ2gKhd9BDT)"
cover: "[Cover - Mr. Morale & The Big Steppers](https://i.scdn.co/image/ab67616d0000b2732e02117d76426a08ac7c174f)"
tags:
  - songs
---
```
which visually translates to: 
![image](https://github.com/user-attachments/assets/55e32a56-e750-479a-96fe-f58e44f73e9e)

Thanks for your help!

**Comment by studiowebux** [comment]
Hello @funkenhausen 

I added an enter and removed the single quote and seemed to have worked : 

```md
---
artists:
{{ artists_formatted:  - "[[:]]" }}
album: "[[{{ album }}]]"
url: "{{ song_link }}"
cover: "{{ album_cover_link_large }}"
tags:
  - songs
---
```

This is because I did not add an enter for the first element, I can add it if you need,
Based on what I read, the output for the frontmatter thingy must be like this : 

```
tags:
- option 1
- option 2
```

Not sure about the single quote tho.

Let me know if you want me to change something

**Comment by funkenhausen** [comment]
Huh, I guess I was wrong. I thought the single quotes was needed for it to work because when I didn't put single quotes on the template, it outputs it like this: 

![image](https://github.com/user-attachments/assets/834e9d3f-6468-44c2-8033-59a858a2da98)

so I thought it was an error and couldn't read the file properly. But when I tried it as is, it outputted what I wanted. So really it already worked when you released the update. I apologize for the inconvenience. Thanks for the help again!

**Comment by studiowebux** [comment]
Morning !

No problem,

Feel free to reopen this issue if anything else 
have a nice day
