### ISSUE TITLE
cannot read properties error

### ISSUE THREAD

**Issue by notuntoward** [studiowebux/obsidian-spotify-link#5]
If was able to get it working, this would be great!

I was able to:

- configure the Spotify API, 
- the `{{ song_name }}` template, 
- and successfully connect Obsidian to Spotify, according to the icon in the ribbon, 
- and then I saw the "Spotify connected" message in the lower left hand corner.

Unfortunately, when I run "`Append Spotify currently playing track with timestsamp`, I get the error popup below:

![image](https://github.com/studiowebux/obsidian-spotify-link/assets/3851891/0b5d8071-1087-46ff-84a5-8b99bfe4d85d)

I ran the logstravaganza plugin, and got this log: [console-log.DESKTOP-VPFVCTB.md](https://github.com/studiowebux/obsidian-spotify-link/files/14796601/console-log.DESKTOP-VPFVCTB.md)

Any advice?

**Comment by studiowebux** [comment]
Hello again !

are you listening to an episode (podcast)
I received this issue : https://github.com/studiowebux/obsidian-spotify-link/issues/6

and it seems to be similar to what you describe

**Comment by studiowebux** [comment]
I published the v1.2.0, you can update the plugin directly in Obsidian.

The documentation is also up-to-date: https://studiowebux.github.io/obsidian-plugins-docs/docs/category/plugin-spotify-link

Let me know if it solves the issue

**Comment by notuntoward** [comment]
Yes, I was listening to a podcast, and now, after your update, podcast links work perfectly.  Thanks for the extremely quick fix!
