### ISSUE TITLE
Error inserting data when listening to an podcast episode

### ISSUE THREAD

**Issue by turing-ex-machina** [studiowebux/obsidian-spotify-link#6]
When I try to use any of the plugins command when listening to a podcast on Spotify I get the following error message:

```
Cannot read property of null (reading 'name').
```

Can this be fixed? The plugin works normally when I am listening to a song.

**Comment by studiowebux** [comment]
Hello!

Thanks for opening this feature request

I will take a look and update this ticket

**Comment by studiowebux** [comment]
I published the v1.2.0, you can update the plugin directly in Obsidian.

The documentation is also up-to-date: https://studiowebux.github.io/obsidian-plugins-docs/docs/category/plugin-spotify-link

i've added two new commands to tackle the podcast specification as well as a new template so you can build the UI you need, if you need another features or changes let me know

**Comment by turing-ex-machina** [comment]
Very nice, thank you. Is it possible to expose the current timestamp of the episode being played to the templates? Can I open a new feature request for it?

**Comment by studiowebux** [comment]
not as for now but it is coming soon,
I will update the ticket as soon as it is supported

**Comment by chasehelton** [comment]
@turing-ex-machina @studiowebux I created a pull request to add this as I was also looking for a similar functionality. It exposes the progress_ms field as milliseconds, seconds, and minutes/seconds. You can find it here: https://github.com/studiowebux/obsidian-spotify-link/pull/10

**Comment by turing-ex-machina** [comment]
@studiowebux will close this issue then, since the original issue was resolved. Thanks.
